Backend/Backend/urls.py
from django.contrib import admin
from django.urls import path, include
from ebayItems.tasks import ebay_badewanne_update


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('ebayItems.urls', 'ebayItems'), namespace='ebayItems')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

ebay_badewanne_update(repeat=900, repeat_until=None)

Backend/ebayItems/urls.py
"""
    url module
"""

from django.urls import path
from .views import (
    FilteredEbayItemListView,
    item_badewanne,
    EbayItemsListView,
    EbayItemsUpdateView
)


urlpatterns = [
    path('', FilteredEbayItemListView.as_view(), name='ebay_index'),
    path('items/', EbayItemsListView.as_view(), name='items-list'),
    path('items/<int:pk>/', EbayItemsUpdateView.as_view(), name='items-partial-update'),
    path('badewanne/', item_badewanne, name='badewanne'),
]

Backend/ebayItems/models.py
"""
This Module defines the table to store ebay item data.
"""

import datetime
from enum import Enum

from django.db import models
from django.utils.timezone import get_current_timezone
import django_filters
from django_filters import rest_framework as filters
from django_filters.filters import forms


class BWStageEnum(Enum):
    """
    Enum class to define various item status
    """
    BW_STAGE0 = 'BW_STAGE0'
    BW_STAGE1_30D = 'BW_STAGE1_30D'
    BW_STAGE2_20D = 'BW_STAGE2_20D'
    BW_STAGE3_10D = 'BW_STAGE3_10D'
    BW_STAGE4_0D = 'BW_STAGE4_0D'
    BW_STAGE5_5I = 'BW_STAGE5_5I'
    BW_STAGE6_10I = 'BW_STAGE6_10I'
    BW_BLOCKED = 'BW_BLOCKED'
    BW_TOBLOCK = 'BW_TOBLOCK'
    BW_READY = 'BW_READY'
    NORMAL = 'NORMAL'
    LRW_LIST = 'LRW_LIST'


class EbayItem(models.Model):
    """
    Create table EbayItem to store the item infos
    """
    item_no = models.BigIntegerField(
        null=False, verbose_name='ItemNo', db_column='ItemNo'
    )
    item_id = models.CharField(
        max_length=50, null=False, verbose_name='EbayItemID', db_column='ItemID'
    )
    auction_id = models.CharField(
        max_length=50, null=False, verbose_name='AuctionID', db_column='AuctionID'
    )
    sku = models.CharField(max_length=250, null=False, verbose_name='SKU', db_column='SKU')
    item_description = models.CharField(
        max_length=1000, null=False, verbose_name='Description', db_column='ItemDescription'
    )
    sales_goal_reached_in_last14days = models.FloatField(
        null=False, max_length=10, verbose_name='SalesL14',
        db_column='SalesGoalReachedInLast14Days'
    )
    sales_goal_reached_in_last7days = models.FloatField(
        null=False, max_length=10, verbose_name='SalesL7',
        db_column='SalesGoalReachedInLast7Days'
    )
    sales_goal_reached_mtd = models.FloatField(
        null=False, max_length=10, verbose_name='SalesMTD',
        db_column='SalesGoalReachedMTD'
    )
    cogs_24h_vs_7d = models.FloatField(
        null=False, max_length=10, verbose_name='COGS24HVS7D',
        db_column='COGS24HVS7D'
    )
    channel = models.CharField(
        null=False, max_length=200, verbose_name='Channel', db_column='Channel'
    )
    country = models.CharField(
        null=False, max_length=200, verbose_name='Country', db_column='Country'
    )
    stock = models.IntegerField(null=False, verbose_name='Stock', db_column='Stock')
    lrw = models.IntegerField(null=False, verbose_name='LRW', db_column='LRW')
    fc = models.IntegerField(null=False, verbose_name='FC', db_column='FC')
    item_ranking_today = models.IntegerField(
        null=False, verbose_name='Rank', db_column='ItemRankingToday'
    )
    item_status = models.CharField(
        max_length=15,
        choices=[(tag, tag.value) for tag in BWStageEnum],
        default=BWStageEnum.NORMAL.value,
        verbose_name='Status',
        db_column='ItemStatus'
    )
    our_purchase_price = models.FloatField(
        null=False, max_length=10, verbose_name='PPrice',
        db_column='OurPurchasePrice'
    )
    current_sale_price = models.FloatField(
        null=False, max_length=10, verbose_name='CPrice',
        db_column='CurrentSalePrice'
    )
    suggested_sale_price = models.FloatField(
        null=False, max_length=10, verbose_name='SPrice',
        db_column='SuggestedSalePrice')
    last_humansetprice_before_badewanne = models.FloatField(
        null=False, max_length=10, verbose_name='LHSPrice',
        db_column='LastHumanSetPriceBeforeBadewanne'
    )
    new_price = models.FloatField(
        null=False, max_length=10, verbose_name='NewPrice',
        db_column='NewPrice'
    )
    dio1 = models.IntegerField(null=False, verbose_name='DIO1', db_column='DIO1')
    dio2 = models.IntegerField(null=False, verbose_name='DIO2', db_column='DIO2')
    last_bw_start_date = models.DateTimeField(
        default=datetime.datetime(1970, 1, 1, 0, 0, 0, 0, tzinfo=get_current_timezone()),
        verbose_name='LBWSDate',
        db_column='LastBWStartDate'
    )
    last_bw_end_date = models.DateTimeField(
        default=datetime.datetime(1970, 1, 1, 0, 0, 0, 0, tzinfo=get_current_timezone()),
        verbose_name='LBWEDate',
        db_column='LastBWEndDate'
    )
    objects = models.Manager()


class EbayItemsFilter(filters.FilterSet):
    """
    Model filter which defines the filter fields and lookup rules.
    """

    class Meta: # pylint: disable=too-few-public-methods
        """
        Meta
        """
        model = EbayItem
        fields = {
            'item_no': ['exact'],
            'item_id': ['exact'],
            'auction_id': ['exact'],
            'country': ['exact']
        }

    item_status = django_filters.LookupChoiceFilter(
        field_class=forms.CharField,
        field_name='item_status',
        lookup_choices=[
            ('exact', 'Equals'),
            ('startswith', 'Startswith')
        ]
    )
    rank = django_filters.LookupChoiceFilter(
        field_class=forms.IntegerField,
        field_name='item_ranking_today',
        lookup_choices=[
            ('exact', 'Equals'),
            ('gt', 'Greater than'),
            ('lt', 'Less than'),
        ]
    )
    sales_l7 = django_filters.LookupChoiceFilter(
        field_class=forms.FloatField,
        field_name='sales_goal_reached_in_last7days',
        lookup_choices=[
            ('exact', 'Equals'),
            ('gt', 'Greater than'),
            ('lt', 'Less than'),
        ]
    )
    sales_l14 = django_filters.LookupChoiceFilter(
        field_class=forms.FloatField,
        field_name='sales_goal_reached_in_last14days',
        lookup_choices=[
            ('exact', 'Equals'),
            ('gt', 'Greater than'),
            ('lt', 'Less than'),
        ]
    )

    sales_mtd = django_filters.LookupChoiceFilter(
        field_class=forms.FloatField,
        field_name='sales_goal_reached_mtd',
        lookup_choices=[
            ('exact', 'Equals'),
            ('gt', 'Greater than'),
            ('lt', 'Less than'),
        ]
    )

    fc = django_filters.LookupChoiceFilter(
        field_class=forms.IntegerField,
        field_name='fc',
        lookup_choices=[
            ('exact', 'Equals'),
            ('gt', 'Greater than'),
            ('lt', 'Less than'),
        ]
    )

    stock = django_filters.LookupChoiceFilter(
        field_class=forms.IntegerField,
        field_name='stock',
        lookup_choices=[
            ('exact', 'Equals'),
            ('gt', 'Greater than'),
            ('lt', 'Less than'),
        ]
    )

Backend/ebayItems/views.py
"""
ebayItems's views, which defines how to response the user request.
"""

import logging
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.utils.timezone import get_current_timezone
from django_filters.views import FilterView
from django_filters.rest_framework import DjangoFilterBackend
from django_tables2.views import SingleTableMixin
from django_tables2.export.views import ExportMixin
from rest_framework.mixins import UpdateModelMixin
from rest_framework import generics

from .serializers import EbayItemsSerializer
from .models import EbayItem, EbayItemsFilter, BWStageEnum
from .tables import EbayItemTable
from .tasks import badewanne_process_tracking


LOGGER = logging.getLogger(__name__)


class FilteredEbayItemListView(LoginRequiredMixin, SingleTableMixin, ExportMixin, FilterView):
    """
    Display filter form and item detail table
    """
    login_url = '/accounts/login/'
    table_class = EbayItemTable
    model = EbayItem
    template_name = 'ebayItems/ebayItems.html'

    filterset_class = EbayItemsFilter

@login_required()
def item_badewanne(request):
    """
        Function when user clicked start or end badewanne
    :param request:
    :return:
    """
    if request.method == "POST":
        pks = request.POST.getlist("selection")
        if "start-badewanne" in request.POST:
            items = EbayItem.objects.filter(
                pk__in=pks,
                item_status=BWStageEnum.BW_READY.value,
            )
            LOGGER.info("Items to start Badewanne: %s", items)
            items.update(item_status=BWStageEnum.BW_STAGE0.value,
                         last_bw_start_date=datetime.now(tz=get_current_timezone()))
            badewanne_process_tracking(list(items.values_list('id', flat=True)), schedule=5)
        elif "stop-badewanne" in request.POST:
            items = EbayItem.objects.filter(
                pk__in=pks,
                item_status__startswith='BW_STAGE',
            )
            LOGGER.info("Items to stop Badewanne: %s", items)
            items.update(item_status=BWStageEnum.BW_TOBLOCK.value)
            badewanne_process_tracking(list(items.values_list('id', flat=True)), schedule=5)
    return redirect(request.META.get('HTTP_REFERER'))


class EbayItemsListView(generics.ListAPIView):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = EbayItem.objects.all()
    serializer_class = EbayItemsSerializer
    filter_backends = [DjangoFilterBackend]
    filterset_class = EbayItemsFilter


class EbayItemsUpdateView(generics.GenericAPIView, UpdateModelMixin):
    """
        REST API Update View
    """
    queryset = EbayItem.objects.all()
    serializer_class = EbayItemsSerializer

    def put(self, request, *args, **kwargs):
        """
            REST API put
        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        return self.partial_update(request, *args, **kwargs)

Backend/ebayItems/templates/ebayItems/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>AI Hub</title>
    {% load static%}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#content').width($(window).width() - 290);
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');

                if ($('#sidebar').attr('class') == 'active') {
                    $('#content').width($(window).width() - 130);
                } else {
                    $('#content').width($(window).width() - 290);
                }
            });
        });
    </script>
    {% block head %}
    {% endblock %}
</head>
<body>
    <div class="wrapper">
        <!-- Sidebar  -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3>Dynamic Pricing</h3>
                <strong>DP</strong>
            </div>

            <ul class="list-unstyled components">
                <li class="active">
                    <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                        <i class="fas fa-home"></i>
                        Badewanne
                    </a>
                    <ul class="collapse list-unstyled" id="homeSubmenu">
                        <li>
                            <a href="{% url 'ebayItems:ebay_index' %}">Ebay</a>
                        </li>
                    </ul>
                </li>
            </ul>

        </nav>

        <!-- Page Content  -->
        <div id="content">
            <div>
                <nav class="navbar navbar-expand-lg navbar-light bg-light">
                    <div class="container-fluid">

                        <button type="button" id="sidebarCollapse" class="btn btn-info">
                            <i class="fas fa-align-left"></i>
                            <span>Toggle Sidebar</span>
                        </button>
                        <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <i class="fas fa-align-justify"></i>
                        </button>

                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="nav navbar-nav ml-auto">
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'logout' %}">
                                        <i class="fas fa-sign-out-alt"></i>
                                        <span>Logout</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                <nav>
            </div>

            <div style="display:block; margin-left:auto; margin-right: auto;">
                {% block content %}
                {% endblock %}
            </div>

        </div>
    </div>
</body>
</html>

Backend/ebayItems/templates/ebayItems/ebayItems.html
{% extends "ebayItems/base.html" %}
{% block head %}
    {% load render_table from django_tables2 %}
    {% load bootstrap4 %}
    {% load querystring from django_tables2 %}
    <script language="JavaScript">
            function toggle(source) {
                checkboxes = document.getElementsByName('selection');
                for(var i in checkboxes)
                    checkboxes[i].checked = source.checked;
            }
        </script>
{% endblock %}

{% block content %}
    {% if filter %}
            <form action="" method="get" class="form form-inline">
                {% bootstrap_form filter.form layout='inline' %}
                {% buttons %}
                    <input class="btn btn-link" type="submit" value="Filter">
                {% endbuttons %}
            </form>
    {% endif %}
        <form action="{% url 'ebayItems:badewanne' %}" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-12 col-sm-12 col-md-4">
                    <input class="btn btn-primary" type="submit" name="start-badewanne" value="Start Badewanne">
                </div>
                <div class="col-12 col-sm-12 col-md-4">
                    <input class="btn btn-danger" type="submit" name="stop-badewanne" value="Stop Badewanne">
                </div>
                <div class="col-12 col-sm-12 col-md-4">
                    <a href="{% querystring '_export'='xlsx' %}" role="button" class="btn btn-primary">Download XLSX</a>
                </div>
            </div>

            <div class="table-responsive">
                {% render_table table %}
            </div>
        </form>

{% endblock %}